---
title: "Oxford Palettes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Oxford Palettes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo = FALSE}
library(oxthema)
```

Based on the [University of Oxford](https://ox.ac.uk)'s [visual identity guidelines](https://communications.web.ox.ac.uk/communications-resources/visual-identity/identity-guidelines) and the carefully curated colour groups of the official University [theme packs](https://communications.web.ox.ac.uk/communications-resources/visual-identity/identity-guidelines/theme-packs), the following palettes are available from this package:

## Heritage

```{r oxford-palettes-heritage-code}
oxford_theme_palettes()$heritage
```

```{r oxford-palettes-heritage-show, echo = FALSE, fig.height = 1, fig.align = "center"}
structure(oxford_theme_palettes()$heritage, class = "palette", name = "heritage")
```

## Contemporary

```{r oxford-palettes-contemporary-code}
oxford_theme_palettes()$contemporary
```

```{r oxford-palettes-contemporary-show, echo = FALSE, fig.height = 1, fig.align = "center"}
structure(oxford_theme_palettes()$contemporary, class = "palette", name = "contemporary")
```

## Celebratory

```{r oxford-palettes-celebratory-code}
oxford_theme_palettes()$celebratory
```

```{r oxford-palettes-celebratory-show, echo = FALSE, fig.height = 1, fig.align = "center"}
structure(oxford_theme_palettes()$celebratory, class = "palette", name = "celebratory")
```

## Corporate

```{r oxford-palettes-corporate-code}
oxford_theme_palettes()$corporate
```

```{r oxford-palettes-corporate-show, echo = FALSE, fig.height = 1, fig.align = "center"}
structure(oxford_theme_palettes()$corporate, class = "palette", name = "corporate")
```

## Innovative

```{r oxford-palettes-innovative-code}
oxford_theme_palettes()$innovative
```

```{r oxford-palettes-innovative-show, echo = FALSE, fig.height = 1, fig.align = "center"}
structure(oxford_theme_palettes()$innovative, class = "palette", name = "innovative")
```
